import Head from "next/head";
import Headpage from "../../components/headpage";

export default function Shop() {
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Headpage title="Shop" description=" " />
    </>
  );
}
