// dependencies
import Head from "next/head";
import Link from "next/link";

// components
import Headpage from "../../src/components/headpage";

// database
import Product from "../../src/models/product";
import db from "../../src/utils/db";

// nucleus
export default function Shop(props) {
  const { productsData } = props;
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Headpage title="Shop" description=" " />
      <section data-scroll-section className="shop-page">
        <div className="container -default">
          <div className="shop-list-wrap">
            {productsData.map((item, index) => (
              <div key={index} className="product-wrap-item">
                <Link href={`/shop/${item.slug}`}>
                  <a className="img-wrap">
                    <img src={item.image} alt={item.name} />
                  </a>
                </Link>
                <h4 className="title">{item.name}</h4>
                <span className="price">${item.price}</span>
                <button className="add">Add to card</button>
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}

export async function getServerSideProps() {
  await db.connect();
  const products = await Product.find({}).lean();
  await db.disconnect();
  return {
    props: {
      productsData: products.map(db.convertDocToObj),
    },
  };
}
