export const nav = [
  { title: "About", link: "/" },
  { title: "Services", link: "/services" },
  { title: "FAQs", link: "/faqs" },
  { title: "Shop", link: "/shop" },
];

export const services = [
  {
    title: "Brand strategy & identity",
    description:
      "Платформа бренда, digital-стратегия, фирменный стиль, нейминг",
    img: "/media/1.jpg",
  },
  {
    title: "Digital & mobile production",
    description:
      "Проектирование и архитектура, UX/UI design, Front-end, Back-end, DevOps",
    img: "/media/1.jpg",
  },
  {
    title: "Content production",
    description: "3D, motion, AR, photo, video, copyright, illustrations",
    img: "/media/1.jpg",
  },
  {
    title: "Research & analytics",
    description: "Маркетинговый анализ, UX-аналитика, CJM",
    img: "/media/services/04.jpg",
  },
];

export const shop = [
  {
    name: "Solarvet light",
    slug: "solarvet-light",
    category: "Light",
    image: "/media/shop/1.png",
    isFeatured: true,
    featuredImage: "/media/shop/1.png",
    price: 70,
    brand: "IKEA",
    rating: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: "A great product for Christmas",
  },
  {
    name: "Strala",
    slug: "strala",
    category: "Light",
    image: "/media/shop/2.png",
    isFeatured: true,
    featuredImage: "/media/shop/2.png",
    price: 80,
    brand: "IKEA",
    rating: 4.2,
    numReviews: 10,
    countInStock: 14,
    description: "A great product for Christmas",
  },
  {
    name: "Svartra",
    slug: "svartra",
    category: "Light",
    image: "/media/shop/3.png",
    price: 90,
    brand: "IKEA",
    rating: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: "A great product for Christmas",
  },
  {
    name: "Utsund",
    slug: "utsund",
    category: "LEDs",
    image: "/media/shop/4.png",
    price: 90,
    brand: "IKEA",
    rating: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: "Smart looking pants",
  },
  {
    name: "Godafton",
    slug: "godafton",
    category: "LEDs",
    image: "/media/shop/5.png",
    price: 95,
    brand: "IKEA",
    rating: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: "A great product for Christmas",
  },
  {
    name: "Ledljus",
    slug: "ledljus",
    category: "LEDs",
    image: "/media/shop/6.png",
    price: 75,
    brand: "IKEA",
    rating: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: "A great product for Christmas",
  },
];
