// dependencies
import Head from "next/head";

// components
import SectionDescription from "../src/components/sections/section-description";
import Headpage from "../src/components/headpage";

// database
import { q } from "../src/utils/data";

// nucleus
export default function Faqs() {
  return (
    <>
      <Head>
        <title>Faqs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Headpage
        title="FAQs"
        description="As coworking spaces, we are not just space providers: we enhance the working spaces by being the best companion. Silversquare is a binding agent between people, skills, and knowledge."
      />
      <section
        data-scroll-section
        data-scroll-section-inview
        className="image -full"
      >
        <img src="/media/03.jpeg" alt="img" />
      </section>
      <SectionDescription data={q} subtitle="Subtitle" />
    </>
  );
}
