// dependencies
import Head from "next/head";
import Image from "next/image";

// components
import Headpage from "../src/components/headpage";

// database
import { services } from "../src/utils/data";

// nucleus
export default function Services() {
  return (
    <>
      <Head>
        <title>Satoshi - Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Headpage
        title="Services"
        description="As coworking spaces, we are not just space providers: we enhance the working spaces by being the best companion. Silversquare is a binding agent between people, skills, and knowledge."
      />

      <section
        data-scroll-section
        data-scroll-section-inview
        className="image -full"
      >
        <img src="/media/03.jpeg" alt="img" />
      </section>

      <section
        data-scroll-section
        data-scroll-section-inview
        className="services-blocks"
      >
        {services.map((item, index) => (
          <div key={index} className="box">
            <div className="container -default">
              <div className="img-wrap">
                <Image src={item.img} quality={100} layout="fill" alt="img" />
              </div>
              <h3>{item.title}</h3>
              <span>{item.description}</span>
            </div>
          </div>
        ))}
      </section>
    </>
  );
}
