import Head from "next/head";
import Image from "next/dist/client/image";
import MotiveImage from "../components/sections/image";
import Headpage from "../components/headpage";

import { services } from "./api/data";

console.log(services);

export default function Services() {
  return (
    <>
      <Head>
        <title>Satoshi - Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Headpage title="Services" description=" " />

        <section className="image -full">
          <MotiveImage src="/media/02.jpg" />
        </section>

        <section className="services-blocks">
          {services.map((item, index) => (
            <div key={index} className="box">
              <div className="container -default">
                <div className="img-wrap">
                  <Image src={item.img} quality={100} layout="fill" />
                </div>
                <h3>{item.title}</h3>
                <span>{item.description}</span>
              </div>
            </div>
          ))}
        </section>
      </main>
    </>
  );
}
